### ISSUE TITLE
Methods with no GET/POST etc inside Controller class

### ISSUE THREAD

**Issue by Tijs-2** [dinject/javalin-generator#31]
Hi Rob,

Something has changed with the new version.
The following code compiles with version 1.18 of the generator but not with the newest master branch.

`
  import io.dinject.controller.Controller;
  import io.dinject.controller.Path;
  
  @Controller
  @Path("/hallo")
  public class api {
      public String test() {
          return "TEST";
      }
  }
`

It took me some time find it but it appears that it goes wrong in the constructor of the MethodReader
and than specifically this line: 
    `this.pathSegments = PathSegments.parse(Util.combinePath(bean.getPath(), webMethodPath));`
Even more specifically in the io.dinject.webroutegen.Util --> combinePath 
because the webMethodPath is null

For a quick fix I just changed the lines inside the MethodReader from
`
      this.pathSegments = PathSegments.parse(Util.combinePath(bean.getPath(), webMethodPath));
`
into

    if(isWebMethod())
      this.pathSegments = PathSegments.parse(Util.combinePath(bean.getPath(), webMethodPath));
    else
      this.pathSegments = PathSegments.EMPTY;

But no idea if I break something else, and if this is suppose to work like this

**Comment by rbygrave** [comment]
Ah ok.  I would expect an `@Get` to be required on the method.  If 1.18 was mapping that method to an HTTP GET that would not be expected but I'll try to have a look at that over the next couple of days (and get those PR's reviewed and merged)

**Comment by Tijs-2** [comment]
Well it wasn't mapping it to a GET method but it just ignored the method. Which would be nice because then you can have code shared between 2 get methods.


For example:

    @controller
    @path("/hallo")
    public class api {
        public String test() {
            return generateSomethingDifficult(String value);
        }

        public String test() {
                return generateSomethingDifficult(String value);
        }
   
       private String generateSomethingDifficult(String value) {
           return value;
       }
    }

**Comment by rbygrave** [comment]
```Caused by: java.lang.NullPointerException
    at io.dinject.webroutegen.Util.combinePath (Util.java:42)
    at io.dinject.webroutegen.MethodReader.<init> (MethodReader.java:65)
    at io.dinject.webroutegen.ControllerReader.readMethod (ControllerReader.java:209)
    at io.dinject.webroutegen.ControllerReader.readMethod (ControllerReader.java:198)
    at io.dinject.webroutegen.ControllerReader.read (ControllerReader.java:167)
    at io.dinject.webroutegen.BaseProcessor.writeControllerAdapter (BaseProcessor.java:91)
    at io.dinject.webroutegen.BaseProcessor.process (BaseProcessor.java:56)
```
When run with `mvn -X clean test` and with controller of:

```java
package org.example.myapp.web;

import io.dinject.controller.Controller;
import io.dinject.controller.Path;

@Controller
@Path("hallo")
public class Hallo {

  public String getStuff() {
    return "Hallo";
  }
}
```

**Comment by rbygrave** [comment]
> Something has changed with the new version.

Yes, this was a regression as we moved a lot of derived/calculated properties of MethodReader into it's constructor and made them final.  

Pushed the Javalin and Helidon example projects to give us integration tests coverage going forward.
