### ISSUE TITLE
HTTP status code can't be overwritten by route handler

### ISSUE THREAD

**Issue by nschlehe** [dinject/javalin-generator#4]
Generated controller class sets ctx.status after calling the registered route handler and overwrites previously set status code. An easy fix would be moving the status() call before the handler turning the behaviour to a fallback.

```java
ApiBuilder.post("/login", ctx -> {
      controller.login(ctx);
      ctx.status(201);
});
```

**Comment by rbygrave** [comment]
Fixed with the provided PR - thanks !!
