### ISSUE TITLE
DInject is not working with Gradle 5.3.1

### ISSUE THREAD

**Issue by NotakuDotMe** [dinject/javalin-generator#6]
I tried to run the project with gradle 5.3.1 (and some other 5.x) versions, but gradle is not working.
Javalin is working without problems, but there are no Beans registered.
The SystemContext.getBean can't use defined classes and the automatic Bean registrator is not working.
I think that the problem is the pre-compiler, they don't compile an register the beans.
My fix is, to download the gradle wrapper version 4.10.

**Comment by rbygrave** [comment]
Ok thanks.  I'll try to look at this over the weekend.  Cheers.

**Comment by rbygrave** [comment]
I've put up a Gradle 5 example for Java and Kotlin at - https://github.com/dinject/examples

They are both working well (but I do need to release 1.6 of the controller and generator)

**Comment by NotakuDotMe** [comment]
Thanks!

I don't know why, but it worked for me a long time, but after a few weeks, they didn't compile anymore.
A friend of me had the same issue.

Now it's not working anymore, either Gradle 4 or 5.

Best regards. :)

**Comment by rbygrave** [comment]
Have you git cloned the examples project and run the gradle projects there?

**Comment by NotakuDotMe** [comment]
No, I worked on a project for my university, so after 8 hours of debugging, I decided to remove DInject.
But I can try to reproduce the issue.
I'm going to try the example, maybe I can find out a little bit more.

The problem is, the controllers worked perfectly for a long time, after a few weeks, DInject didn't compile anymore.
There was no logging message either, I cleaned Gradle and switched the version. So dinject worked well, for a few weeks. But after some time, Gradle 4 or 5 didn't worked anymore, I definitely didn't changed any controllers. Really strange.

I will let you know, if I find anything.
And another guy had the same problem.

Oh and I'm using NixOS as operating system, the other guy is using Ubuntu.

Thanks @rbygrave. :)

**Comment by rbygrave** [comment]
Hi @NotakuDotMe ... Gradle is potentially not reporting / logging an error (in the APT processing for dinject-generator).  So in the case when it isn't working try to get Gradle to log output and see if there is an error (we'd expect one if there isn't any generated code).

**Comment by NotakuDotMe** [comment]
Okay, I've been found the commit.
On my project: https://gitlab.com/thm-team42/backend/ with the commit fd5cfe52, DInject is not working.
I'm using the gradle wrapper with version 5.3.1.

My gradle-wrapper.properties
```json
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.3.1-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

```


In Javalin, in register the controller with a peek, to debug:
```java
.routes(() -> SystemContext.getBeans(WebRoutes.class).stream().peek(System.out::println).forEach(WebRoutes::registerRoutes))
```
On working instances, the peek will show me the controller instances, but in that version, Dinject is not working, so there is no output. :(

In the class projects.pis.team42.GameController, I created a method called test:
```java
@Controller
@Path("/game")
public class GameController {
    ...
    
    @Get("/test")
    public String test() {
        return "Hello?";
    }
}
```


But no controller methods are working, because DInject is not working.
I can try whatever I want, no controller will work and no Singleton will work.
In the past, I got a giant logtrace from DInject, but that worked. I also got the peek message from the main class.

[run.log](https://github.com/dinject/javalin-generator/files/3294388/dinject.log) The console log with ./gradlew run
[debug.log](https://github.com/dinject/javalin-generator/files/3294395/debug.log) The debug with ./gradlew -d run

**Comment by rbygrave** [comment]
> with the commit fd5cfe52,

Can you provide a link to the commit?  I don't see that commit for
`fd5cfe52`

**Comment by NotakuDotMe** [comment]
Sure, no problem. You can clone that version. :)
https://gitlab.com/thm-team42/backend/commit/fd5cfe523820d2d646e333975f810705babbdc6b

**Comment by rbygrave** [comment]
Well ...
```gradle
    // DInject
    compile 'io.dinject:dinject:1.1'
    compile 'io.dinject:dinject-controller:1.1'
    compileOnly 'io.dinject:dinject-generator:1.1'
    compileOnly 'io.dinject:javalin-generator:1.1'
```
... those compileOnly `generator` dependencies should instead be annotationProcessor.
Refer to the (relatively new) documentation at: https://dinject.io/docs/gradle
See Example: https://github.com/dinject/examples/blob/master/javalin-gradle-java-basic/build.gradle

Also, you can bump dinject and dinject-generator to 1.8 
and bump dinject-controller and javalin-generator to 1.6

No, it won't work with compileOnly as those are `annotation processors` (I'm thinking you did that based on the maven docs or something).

Cheers, Rob.

**Comment by NotakuDotMe** [comment]
Oh my god! Thank you so much @rbygrave 
I've searched hours and yeah... I did that, because it was in the maven docs. :)
The gradle docs is new, nice! :D
Thanks! ^^

**Comment by rbygrave** [comment]
Yeah no problem.  I suspect that Gradle `somewhat` supported annotation processors via normal classpath in the past (given some things of read just recently) hence I think it kind of worked in the past.  It does seem that we should be using `annotationProcessor` going forward though.

Cheers, Rob.
